- name: Demo on variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: "{{ URL }} is the URL"

#- name: Demo on file variables
 # hosts: all
 # vars_files:
 #   - sample-vars.yml
 # tasks:
  #  - name: Print URL
  #    ansible.builtin.debug:
   #     msg: URL = {{URL}}

- name: Task level variables
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}
      vars:
        URL: task.example.com

- name: Variable from Inventory
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL == {{ URL }}

- name: Print fact
  hosts: all
  tasks:
    - ansible.builtin.debug:
        msg: Hostname = {{ ansible_hostname}}






- name: Register a variable example
  hosts: all
  tasks:
    - name: Get uptime
      ansible.builtin.shell: uptime
      register: out

    - name: Print out register
      ansible.builtin.debug:
        msg: "{{out}}"

    - name: Declare a fact
      ansible.builtin.set_fact:
        SHELL_STDOUT: "{{out.stdout}}"

    - name: Print shell output from a set_fact variable
      ansible.builtin.debug:
        msg: OUTPUT = {{ SHELL_STDOUT }}